// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: lockstep/proto/room_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_SUCC    ErrorCode = 0 // 成功
	ErrorCode_ERROR_CODE_UNKNOWN ErrorCode = 1 // 未知错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_SUCC",
		1: "ERROR_CODE_UNKNOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_SUCC":    0,
		"ERROR_CODE_UNKNOWN": 1,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lockstep_proto_room_service_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_lockstep_proto_room_service_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_lockstep_proto_room_service_proto_rawDescGZIP(), []int{0}
}

// 统一响应基类
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=lockstep.roomservice.ErrorCode" json:"error_code,omitempty"` // 错误码
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                             // 错误描述（可选，调试用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_lockstep_proto_room_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockstep_proto_room_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_lockstep_proto_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCC
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 创建房间请求
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomConfig    *RoomConfig            `protobuf:"bytes,1,opt,name=room_config,json=roomConfig,proto3" json:"room_config,omitempty"`      // 房间配置
	PlayerIds     []int32                `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // 指定玩家ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_lockstep_proto_room_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lockstep_proto_room_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_lockstep_proto_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetRoomConfig() *RoomConfig {
	if x != nil {
		return x.RoomConfig
	}
	return nil
}

func (x *CreateRoomRequest) GetPlayerIds() []int32 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

// 房间配置
type RoomConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers    int32                  `protobuf:"varint,1,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`    // 最大玩家数
	MinPlayers    int32                  `protobuf:"varint,2,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`    // 最小玩家数
	FrameRate     int32                  `protobuf:"varint,3,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`       // 帧率
	RetryWindow   int32                  `protobuf:"varint,4,opt,name=retry_window,json=retryWindow,proto3" json:"retry_window,omitempty"` // 重试窗口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomConfig) Reset() {
	*x = RoomConfig{}
	mi := &file_lockstep_proto_room_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConfig) ProtoMessage() {}

func (x *RoomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_lockstep_proto_room_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConfig.ProtoReflect.Descriptor instead.
func (*RoomConfig) Descriptor() ([]byte, []int) {
	return file_lockstep_proto_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *RoomConfig) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomConfig) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *RoomConfig) GetFrameRate() int32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *RoomConfig) GetRetryWindow() int32 {
	if x != nil {
		return x.RetryWindow
	}
	return 0
}

// 创建房间响应
type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                   // 基础响应
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_lockstep_proto_room_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lockstep_proto_room_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_lockstep_proto_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_lockstep_proto_room_service_proto protoreflect.FileDescriptor

const file_lockstep_proto_room_service_proto_rawDesc = "" +
	"\n" +
	"!lockstep/proto/room_service.proto\x12\x14lockstep.roomservice\"s\n" +
	"\fBaseResponse\x12>\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x1f.lockstep.roomservice.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"u\n" +
	"\x11CreateRoomRequest\x12A\n" +
	"\vroom_config\x18\x01 \x01(\v2 .lockstep.roomservice.RoomConfigR\n" +
	"roomConfig\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x05R\tplayerIds\"\x90\x01\n" +
	"\n" +
	"RoomConfig\x12\x1f\n" +
	"\vmax_players\x18\x01 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vmin_players\x18\x02 \x01(\x05R\n" +
	"minPlayers\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x03 \x01(\x05R\tframeRate\x12!\n" +
	"\fretry_window\x18\x04 \x01(\x05R\vretryWindow\"e\n" +
	"\x12CreateRoomResponse\x126\n" +
	"\x04base\x18\x01 \x01(\v2\".lockstep.roomservice.BaseResponseR\x04base\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId*8\n" +
	"\tErrorCode\x12\x13\n" +
	"\x0fERROR_CODE_SUCC\x10\x00\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x012n\n" +
	"\vRoomService\x12_\n" +
	"\n" +
	"CreateRoom\x12'.lockstep.roomservice.CreateRoomRequest\x1a(.lockstep.roomservice.CreateRoomResponseB1Z/github.com/O-Keh-Hunter/kcp2k-go/lockstep/protob\x06proto3"

var (
	file_lockstep_proto_room_service_proto_rawDescOnce sync.Once
	file_lockstep_proto_room_service_proto_rawDescData []byte
)

func file_lockstep_proto_room_service_proto_rawDescGZIP() []byte {
	file_lockstep_proto_room_service_proto_rawDescOnce.Do(func() {
		file_lockstep_proto_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lockstep_proto_room_service_proto_rawDesc), len(file_lockstep_proto_room_service_proto_rawDesc)))
	})
	return file_lockstep_proto_room_service_proto_rawDescData
}

var file_lockstep_proto_room_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lockstep_proto_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lockstep_proto_room_service_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: lockstep.roomservice.ErrorCode
	(*BaseResponse)(nil),       // 1: lockstep.roomservice.BaseResponse
	(*CreateRoomRequest)(nil),  // 2: lockstep.roomservice.CreateRoomRequest
	(*RoomConfig)(nil),         // 3: lockstep.roomservice.RoomConfig
	(*CreateRoomResponse)(nil), // 4: lockstep.roomservice.CreateRoomResponse
}
var file_lockstep_proto_room_service_proto_depIdxs = []int32{
	0, // 0: lockstep.roomservice.BaseResponse.error_code:type_name -> lockstep.roomservice.ErrorCode
	3, // 1: lockstep.roomservice.CreateRoomRequest.room_config:type_name -> lockstep.roomservice.RoomConfig
	1, // 2: lockstep.roomservice.CreateRoomResponse.base:type_name -> lockstep.roomservice.BaseResponse
	2, // 3: lockstep.roomservice.RoomService.CreateRoom:input_type -> lockstep.roomservice.CreateRoomRequest
	4, // 4: lockstep.roomservice.RoomService.CreateRoom:output_type -> lockstep.roomservice.CreateRoomResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lockstep_proto_room_service_proto_init() }
func file_lockstep_proto_room_service_proto_init() {
	if File_lockstep_proto_room_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lockstep_proto_room_service_proto_rawDesc), len(file_lockstep_proto_room_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lockstep_proto_room_service_proto_goTypes,
		DependencyIndexes: file_lockstep_proto_room_service_proto_depIdxs,
		EnumInfos:         file_lockstep_proto_room_service_proto_enumTypes,
		MessageInfos:      file_lockstep_proto_room_service_proto_msgTypes,
	}.Build()
	File_lockstep_proto_room_service_proto = out.File
	file_lockstep_proto_room_service_proto_goTypes = nil
	file_lockstep_proto_room_service_proto_depIdxs = nil
}
